spring:
  application:
    name: Eureka-Server
server:
  port: ${EUREKA_PORT:8761}

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
# docker run -d --name eureka-server --network hms-network -p 8761:8761 eureka-server
